/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./../../presentation/components/Comment.vue')['default']
    Filter: typeof import('./../../presentation/components/Filter.vue')['default']
    FilterCheckbox: typeof import('./../../presentation/components/FilterCheckbox.vue')['default']
    Navbar: typeof import('./../../presentation/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('./../../presentation/components/SelectButton.vue')['default']
    Toast: typeof import('./../../presentation/components/Toast.vue')['default']
    Topic: typeof import('./../../presentation/components/Topic.vue')['default']
  }
}
