# Generated by Django 5.0.2 on 2024-03-18 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("qt_likes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField()),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("duvida", "Dúvida"),
                            ("artigo", "Artigo"),
                            ("projeto", "Projeto"),
                            ("oportunidade", "Oportunidade"),
                            ("evento", "Evento"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("administracao", "Administração"),
                            ("biomedicina", "Biomedicina"),
                            ("enfermagem", "Enfermagem"),
                            ("engenharia_civil", "Engenharia Civil"),
                            ("farmacia", "Farmácia"),
                            ("nutricao", "Nutrição"),
                            ("arquitetura_e_urbanimos", "Arquitetura e Urbanimos"),
                            ("direito", "Direito"),
                            ("engenharia_ambiental", "Engenharia Ambiental"),
                            ("letras", "Letras"),
                            ("psicologia", "Psicologia"),
                            (
                                "analise_e_desenvolvimento_de_sistema",
                                "Análise e Desenvolvimento de Sistema",
                            ),
                            ("ciencias_contabeis", "Ciências Contabeis"),
                            ("engenharia_mecanica", "Engenharia Mecânica"),
                            ("gastronomia", "Gastronomia"),
                            ("pedagogia", "Pedagogia"),
                            ("sistemas_de_informacao", "Sistemas de Informação"),
                        ],
                        max_length=90,
                    ),
                ),
                ("qt_likes", models.IntegerField()),
                ("qt_comments", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_Topic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.topic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.comment"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.topic"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="id_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="forum.topic"
            ),
        ),
    ]
