export enum COURSE {
    ADMINISTRACAO = "Administração",
    BIOMEDICINA = "Biomedicina",
    ENFERMAGEM = "Enfermagem",
    ENGENHARIA_CIVIL = "Engenharia Civil",
    FARMACIA = "Farmácia",
    NUTRICAO = "Nutrição",
    ARQUITETURA_E_URBANISMO = "Arquitetura e Urbanismo",
    DIREITO = "Direito",
    ENGENHARIA_AMBIENTAL = "Engenharia Ambiental",
    LETRAS = "Letras",
    PSICOLOGIA = "Psicologia",
    ANALISE_E_DESENVOLVIMENTO_DE_SISTEMA = "Análise e Desenvolvimento de Sistema",
    CIENCIAS_CONTABEIS = "Ciências Contábeis",
    ENGENHARIA_MECANICA = "Engenharia Mecânica",
    GASTRONOMIA = "Gastronomia",
    PEDAGOGIA = "Pedagogia",
    SISTEMAS_DE_INFORMACAO = "Sistemas de Informação",
  }