# Generated by Django 5.0.3 on 2024-03-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_criacao_banco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
