# Generated by Django 5.0.3 on 2024-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.CharField(
                choices=[
                    (1, "Administração"),
                    (2, "Biomedicina"),
                    (3, "Enfermagem"),
                    (4, "Engenharia Civil"),
                    (5, "Farmácia"),
                    (6, "Nutrição"),
                    (7, "Arquitetura e Urbanismo"),
                    (8, "Direito"),
                    (9, "Engenharia Ambiental"),
                    (10, "Letras"),
                    (11, "Psicologia"),
                    (12, "Análise e Desenvolvimento de Sistema"),
                    (13, "Ciências Contábeis"),
                    (14, "Engenharia Mecânica"),
                    (15, "Gastronomia"),
                    (16, "Pedagogia"),
                    (17, "Sistemas de Informação"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[(1, "Masculino"), (2, "Feminino")], max_length=30
            ),
        ),
    ]
